apiVersion: v1
kind: PersistentVolume
metadata:
  name: speedtest-tracker-postgres
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # i.e. mount as RW on a single node
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/k8s/volumes/speedtest-tracker-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ada1
