kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce # i.e. mount as RW on a single node
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: speedtest_tracker
            - name: POSTGRES_USER
              value: speedtest_user
            - name: POSTGRES_PASSWORD
              value: speedtest_password123
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: "./data"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
