kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-data-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  labels:
    app.kubernetes.io/name: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless
    spec:
      containers:
        - name: paperless-ngx
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          ports:
            - containerPort: 8000
              name: web-ui
          env:
            - name: PAPERLESS_PORT # required since k8s would otherwise set this automatically to the svc's address
              value: "8000"
            - name: PAPERLESS_REDIS
              value: redis://redis:6379
            - name: PAPERLESS_DBHOST
              value: postgres
            - name: PAPERLESS_DATA_DIR
              value: /mnt/data-media/data
            - name: PAPERLESS_MEDIA_ROOT
              value: /mnt/data-media/media
            - name: PAPERLESS_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: paperless-options
                  key: PAPERLESS_ADMIN_USER
            - name: PAPERLESS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless-options
                  key: PAPERLESS_ADMIN_PASSWORD
            - name: PAPERLESS_AUTO_LOGIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: paperless-options
                  key: PAPERLESS_AUTO_LOGIN_USERNAME
          volumeMounts:
            - name: data-media
              mountPath: /mnt/data-media
              subPath: "./data-media"
      volumes:
        - name: data-media
          persistentVolumeClaim:
            claimName: paperless-data-media

---

apiVersion: v1
kind: Service
metadata:
  name: paperless
  labels:
    app.kubernetes.io/name: paperless
spec:
  selector:
    app.kubernetes.io/name: paperless
  ports:
    - name: http
      port: 80
      targetPort: web-ui
  type: ClusterIP
