config:
  spec:
    destination:
      server: https://kubernetes.default.svc # tells argo to install apps to the cluster argo is installed in
    source:
      repoURL: https://github.com/jamescallumyoung/homelab.git # this repo's url
      targetRevision: main

projects:
  - name: example
    applications:
      - name: example-app

  - name: selfhosted
    applications:
      - name: paperless
      - name: speedtest-tracker

  - name: cluster-infra
    applications:
      - name: 1password-test
      - name: longhorn
        namespace: longhorn-system
        source:
          chart: longhorn
          repoURL: https://charts.longhorn.io/
          targetRevision: v1.9.1
          helm:
            values: |
              preUpgradeChecker:
                jobEnabled: false
      - name: longhorn-config
